### PR TITLE
Added python example of sending request to model deployed on triton e…

### PR DESCRIPTION
**Pull request by FawadAhmed322**
I wrote an example for sending request to a model deployed on the Nvidia Triton Engine. I used functions that used HTTP requests. Please merge.

### CODE REVIEW

**Comment by FawadAhmed322** [comment]
I just have one confusion right now. This was my first pull request so
excuse my not having understanding of this. I made the pull request from my
main personal github account. The request is in my pull requests and it's
completed as well. But when I go to the ClearML-Serving repo, it points to
a GitHub repo I created on my work email which I don't use. Do you know why
that might be the case?

**Comment by jkhenning** [comment]
I have no idea... I see it pointing to `FawadAhmed322:triton_example` - is that the correct one?

**Comment by FawadAhmed322** [comment]
You're right, I made the pull request from the FawadAhmed322 one and that
is my main one. However when I look at the repo, it shows this in the
image. Basically showing the repo created on my work email instead of my
main one where I created the pull request. I fail to understand why this is
the case.

**Comment by jkhenning** [comment]
GitHub bug? 🙂

**Comment by FawadAhmed322** [comment]
I'll try to contact GitHub support in that case. This isn't really a big
issue but it just kinda sucks. First contribution on github and it isn't
being attributed to my main account publicly, instead being attributed to
an account that I don't even use. Anyway thanks for the help. I'll try to
get help from GitHub support if possible.

**Comment by jkhenning** [comment]
If there's anything we can do - just let me know

**Pull request merged**
