### PR TITLE
added environment vars for advanced usage

### PR DESCRIPTION
**Pull request by besrym**
these were missing, and this step is not listed in the docs

-  now it agrees with the documentation, which says that only the example.env needs to be configured

- tested locally: if these vars are not set, docker just throws some warnings:
image

### CODE REVIEW

**Comment by besrym** [comment]
or we add this additional configuration step to the docs :)

**Comment by jkhenning** [comment]
@besrym I'm not sure I understand - these warnings are usually reported by docker-compose when a variable is references but its value is not provided in environment - why were these mentioned to begin with?

**Comment by besrym** [comment]
@jkhenning yes, exactly but this is not the point here. 

The documentation (advanced setup) states that these variables must be set in the examples.env file. But they also need to be placed in the docker-compose.yml and this took me a decent amount of time to figure that out.

**Comment by jkhenning** [comment]
Ah, got it now 🙂 👍

**Pull request merged**
