### PR TITLE
Use python 3.8 in serving container

### PR DESCRIPTION
**Pull request by milongo**
Hi, my stack uses python 3.8 everywhere and I've just modified the Dockerfile and built the image locally to get my stack to work. I figured it should be easy for you to make an additional image in dockerhub to support python 3.8. Not sure if you need anything else from the PR.

### CODE REVIEW

**Comment by jkhenning** [comment]
Hi @milongo,

If that's the case, I would prefer to have an additional dockerfile to build from 3.8, and not change the existing one...

**Comment by milongo** [comment]
Oh, yes, that makes a lot of sense, sorry. 
What would you say would be a better way of doing this?

**Comment by milongo** [comment]
@jkhenning I provided it as an argument. I think the only thing you'd need to change would be pushing an image built with 3.8 to your hub?

**Comment by jkhenning** [comment]
@milongo makes sense 🙂

**Comment by milongo** [comment]
Cool! @jkhenning please let me know when you get a chance to do that.

**Comment by milongo** [comment]
Hi @jkhenning any updates on this?

**Pull request closed without merging**
